apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.app_name }}
  name: ${{ values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.app_name }}
  template:
    metadata:
      labels:
        app: ${{ values.app_name }}
    spec:
      containers:
      - image: ___IMAGE_URL___@___IMAGE_DIGEST___
        name: ${{ values.app_name }}
        ports:
        - containerPort: 3000
          protocol: TCP
